#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'CachyOS (rolling)' --class cachyos --class gnu-linux --class gnu --class os {
    insmod part_gpt
    insmod btrfs
    set root='hd0,gpt3'
    search --no-floppy --fs-uuid --set=root e18dfec6-dcbd-471f-af67-6de9d5b78782
    linux /@/boot/vmlinuz-linux-cachyos root=UUID=e18dfec6-dcbd-471f-af67-6de9d5b78782 rootflags=subvol=@ nowatchdog nvme_load=YES zswap.enabled=0 splash loglevel=3
    initrd /@/boot/initramfs-linux-cachyos.img
}
menuentry 'CachyOS (LTS)' --class cachyos --class gnu-linux --class gnu --class os {
    insmod part_gpt
    insmod btrfs
    set root='hd0,gpt3'
    search --no-floppy --fs-uuid --set=root e18dfec6-dcbd-471f-af67-6de9d5b78782
    linux /@/boot/vmlinuz-linux-cachyos-lts root=UUID=e18dfec6-dcbd-471f-af67-6de9d5b78782 rootflags=subvol=@ nowatchdog nvme_load=YES zswap.enabled=0 splash loglevel=3
    initrd /@/boot/initramfs-linux-cachyos-lts.img
}
menuentry 'CachyOS (recovery mode)' --class cachyos --class gnu-linux --class gnu --class os {
    insmod part_gpt
    insmod btrfs
    set root='hd0,gpt3'
    search --no-floppy --fs-uuid --set=root e18dfec6-dcbd-471f-af67-6de9d5b78782
    linux /@/boot/vmlinuz-linux-cachyos root=UUID=e18dfec6-dcbd-471f-af67-6de9d5b78782 rootflags=subvol=@ nowatchdog nvme_load=YES zswap.enabled=0 loglevel=4 single
    initrd /@/boot/initramfs-linux-cachyos.img
}
